name: "Cached Checkout with Artifacts"
description: "Caches and checks out the repository using artifacts."
author: pi-xcels

inputs:
  repository:
    description: 'Repository name and owner in the format "owner/repo". Defaults to the current repository.'
    required: false
    default: ${{ github.repository }}
  ref:
    description: "The branch, tag or SHA to checkout. Defaults to the current ref."
    required: false
    default: ${{ github.ref }}
  path:
    description: "Path to checkout the repository into. Defaults to ./checkout."
    required: false
    default: "checkout"
  token:
    description: "Token to use for checkout (e.g., github.token). Required if repository is private."
    required: false
    default: ${{ github.token }}

outputs:
  cache-hit:
    description: "Boolean indicating if the checkout artifact was restored."
    value: ${{ steps.check-artifact.outputs.restored }}

runs:
  using: "composite"
  steps:
    - name: Try to download cached tarball
      id: restore
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: pixcels-checkout-${{ github.sha }}
        path: tmp-artifact

    - name: Check if artifact was restored
      id: check-artifact
      shell: bash
      run: |
        if [ -f "tmp-artifact/checkout.tar.gz" ]; then
          echo "restored=true" >> $GITHUB_OUTPUT
        else
          echo "restored=false" >> $GITHUB_OUTPUT
        fi

    - name: Extract tarball (if restored)
      if: steps.check-artifact.outputs.restored == 'true'
      shell: bash
      run: |
        mkdir -p "${{ inputs.path }}"
        tar -xzf "tmp-artifact/checkout.tar.gz" -C "${{ inputs.path }}"
        rm -rf tmp-artifact

    - name: Checkout repository (if artifact not restored)
      if: steps.check-artifact.outputs.restored != 'true'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        fetch-depth: 0

    - name: Archive checkout to tar.gz (if checkout happened)
      if: steps.check-artifact.outputs.restored != 'true'
      shell: bash
      run: |
        tar -czf checkout.tar.gz -C "${{ inputs.path }}" .

    - name: Upload tarball artifact
      if: steps.check-artifact.outputs.restored != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: pixcels-checkout-${{ github.sha }}
        path: checkout.tar.gz
        retention-days: 1
        include-hidden-files: true
        compression-level: 9

    - name: Move contents to root
      shell: bash
      run: |
        echo "Moving contents of ${{ inputs.path }} to ./"
        cp -a "${{ inputs.path }}/." ./
        rm -rf "${{ inputs.path }}"
